sudo: false
services:
  - docker
addons:
  apt:
    packages:
    - rpm
    - alien
    - dpkg-dev
    - debhelper
    - build-essential
    - jq
language: go
go:
  - 1.6.2
install:
  - bundle
  - go get github.com/GeertJohan/go.rice
  - go get github.com/GeertJohan/go.rice/rice
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 8460774 && go install
    && cd -
  - glide install
  - gem install fpm
script:
  - export GOBIN=$GOPATH/bin
  - IONCHANNEL_SECRET_KEY="" make test
  - IONCHANNEL_SECRET_KEY="" go test -cover $(go list ./... | grep -v '/vendor/')
  - IONCHANNEL_SECRET_KEY="" make coverage
  - GOOS=windows go build -o ion-connect/windows/bin/ion-connect.exe ./
  - rice append --exec ion-connect/windows/bin/ion-connect.exe -i ./lib
  - GOOS=linux go build -o ion-connect/linux/bin/ion-connect ./
  - rice append --exec ion-connect/linux/bin/ion-connect -i ./lib
  - GOOS=darwin go build -o ion-connect/darwin/bin/ion-connect ./
  - rice append --exec ion-connect/darwin/bin/ion-connect -i ./lib
  - cp ion-connect/$(echo "$(uname)" | perl -ne 'print lc')/bin/ion-connect $GOPATH/bin
  - IONCHANNEL_ENDPOINT_URL=$CI_ENDPOINT_URL cucumber -t ~@expected_failure
  - VERSION=`if [ $TRAVIS_TAG -z ]; then echo 'master'; else echo $TRAVIS_TAG; fi`
  - FILE_NAME=ion-connect-$VERSION-$TRAVIS_BUILD_NUMBER
  - cp bin/process-ion-job.sh ion-connect/linux/bin/
  - cp bin/process-ion-job.sh ion-connect/darwin/bin/
  - tar cfvz $FILE_NAME.tar.gz ion-connect
  - ls -l
  - fpm -s dir -t rpm -n ion-connect --iteration $TRAVIS_BUILD_NUMBER -v $VERSION -C
    ion-connect/linux
  - fpm -s dir -t deb -n ion-connect --iteration $TRAVIS_BUILD_NUMBER -v $VERSION -C
    ion-connect/linux
before_deploy:
  - mkdir -p ion-connect/$TRAVIS_TAG
  - cp $FILE_NAME.tar.gz ion-connect/$TRAVIS_TAG/
  - cp $FILE_NAME.tar.gz ion-connect/ion-connect-latest.tar.gz
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make dockerize;
    docker login -e="$HUB_DOCKER_EMAIL" -u="$HUB_DOCKER_USER" -p="$HUB_DOCKER_PASSWORD";
    docker push ionchannel/ion-connect;
    fi
deploy:
  - provider: s3
    bucket: public.ionchannel.io
    region: us-east-1
    skip_cleanup: true
    upload-dir: files/ion-connect
    local_dir: ion-connect
    on:
      tags: true
after_deploy:
  - curl -v -F package=@ion-connect_$VERSION-${TRAVIS_BUILD_NUMBER}_amd64.deb https://$GEMFURY_TOKEN@push.fury.io/ionchannel/
  - curl -v -F package=@ion-connect-$VERSION-$TRAVIS_BUILD_NUMBER.x86_64.rpm https://$GEMFURY_TOKEN@push.fury.io/ionchannel/
notifications:
  slack:
    rooms:
      secure: H4/dc+yBvYYEO/4JdCiMsjCYkffi/87Wfz0/Xe5cyYXUHmYjO9129T7qJgBXbudB/leVWhxe1EgejwQz6o91i7hqpSJjMC2fB+KJcWjqkdM8xxX/hsbyfFAXpq4sPfdxAgikVHfjrg8pktuZZt8wJuTH0kVpRCsRIP/T0qRREYhOA+CUK5rlP1/ewl6p3RIsSTJkLPNNraGEgPeBfQcTWxRmbFqCPmbAZ0AOBtZiNRjyuaS4BxF59Hezv2UkPpamL+X8bZXVpik4F/wYvqnoKnm9IT0DAys5I4LgPWICCdJnMfK2dLPR90QFAkIleh8JhtVOj3QVhWCdHXZjAYJzuw/PFz3peuQ853xfF0zexwSwqx0IOO4en7w4HoyLkX2USerfKtzIqiLIoV26AqA35K/i0YKmYMDhFTIAm6wl1rh8BXKblK5llkker2JhVqTin/VEvuj6yAEY/oIXM3lNiH2jbh0RGWYf3U7qOoFFebV7rdsmZ61B3qZwKCuKFjAnNe8xBBMNuZmU4el0WRVFMdljRUspt3ydhWnoGpXFDquPdU16zz9osnG9mOmub73pH8/dQLrJFspd1VbMTEZmQ/L53QXHtaAaWwGbYjeVte/rYGnu0Wi854SatfaoumJmfWT0IsidKu0wWBMU7Q+NJMi1SSV/4yMJNdBessfD5xs=
